import "mdb-react-ui-kit/dist/css/mdb.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import Login from "./login";
import Nav from "./nav";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${roboto.className} m-5`}>
        <Login />
        <Nav />
        <div className="m-3">{children}</div>
      </body>
    </html>
  );
}
